apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-13"
spec:
  additionalOptions:
    - name: enable-recovery
      value: 'true'
  db:
    database: keycloak
    host: keycloak-pgsql
    passwordSecret:
      key: password
      name: keycloak-db-credentials
    usernameSecret:
      key: username
      name: keycloak-db-credentials
    vendor: postgres
  hostname:
    hostname: sso.{{ .Values.deployer.domain }}
  http:
    httpEnabled: false
    tlsSecret: keycloak-tls
  ingress:
    enabled: false
  instances: 1
  transaction:
    xaEnabled: true
