{{- $realmName := .Values.realm.name | default .Values.tenant.name | lower -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: idp-registration-{{ $realmName }}
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
  labels:
    app.kubernetes.io/component: idp-registration
    tenant: {{ $realmName }}
data:
  spokeRealm: {{ $realmName }}
  hubRealm: {{ .Values.hub.realmName }}
  idpAlias: idp-{{ $realmName }}
