{{ if .Values.datasciencecluster.enabled -}}
---
apiVersion: {{ .Values.datasciencecluster.apiVersion }}
kind: DataScienceCluster
metadata:
  name: {{ .Values.datasciencecluster.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  components:
    {{- .Values.datasciencecluster.components | toYaml | nindent 4 }}
{{- end }}
